### PR TITLE
Update cepheid_tutorial.md

### PR DESCRIPTION
**Pull request by ckuczek**

### CODE REVIEW

**Comment by rkehoe** [comment]
@ckuczek This looks good.  Thanks.  For future, please try to put a brief description in your Pull Requests of what is in the request.  I will make this comment, and than merge following the VSP meeting today.

**Comment by rkehoe** [comment]
@ckuczek I realize you probably have much updated documentation from last August.  Can we get that into rotsesim soon?  I am referencing @jalasker who also followed this issue.

**Comment by gigicu01** [comment]
@rkehoe @jalasker @Zachtmac1 I have added some documentation in Caroline's branch, under the doc directory. Details about this commit can be seen in Commit #20 on Caroline's branch, which is the event displayed above, before this comment. 

Reiterating them below for clarity:

Added documentation about:

- An example of MESA output
- An example input (that comes from MESA's output) that can be used for the phot_per_sec script to generate a light curve
- General info about MESA (a presentation made by Caroline)
- The original plan for the cepeheid simulation from Caroline as well as the associated pseudocode
- Caroline's poster and final presentation

**Comment by rkehoe** [comment]
@gigicu01 Looks good!  Thanks for all those documents.  In the pseudo code, I think we can see that you are working on the def daynight and def abovehorizon codes, while @Zachtmac1 is working on the def weather function.  Right now, the pseudo code envisions all four parts fo the simulator in one class.  However, as you consider your own pseudo codes and sub functions, etc, you may conclude there should be four separate classes.  That is one of the design details you will need to settle once you have a better sense for each piece.

I would merge this PR, but I notice in the docs area that the galaxy simulation tutorial document is mixed in with the variable star stuff from Caroline.  Please create in the rotsesim/docs area two directories like in py/rotse for ‘cepheids’ and for ‘Cosmo’.  Put all the stuff in the former that is already in ‘doc’, except for the galsim_tutorial.rst which you should put into rotsesim/doc/cosmo.  Please comment when that is done and I can merge this PR.

**Comment by gigicu01** [comment]
@rkehoe Requested changes were added. I also added the formatted output of MESA as a separate file. I kept the non-formatted file just in there just in case something was altered but it can probably be deleted later.

**Comment by rkehoe** [comment]
@gigicu01 Directory structure looks good.  I agree the original file can be deleted won the road but good to have now.  As familiarity with MESA increases, we can further improve this area and code area.  I will merge this now.

**Pull request merged**
